### ISSUE TITLE
Speed up boundedrand()

### ISSUE THREAD

**Issue by achan001** [imneme/pcg-c-basic#12]
Instead of calculate threshold using expensive mod, and return results (also with mod),
It is probably faster if the random number is masked with bound bits remaining.

bound--;                                                 // easier to do range <= bound
mask = ~0u >> (32 - (bits of bound));
uint_64 seed = pcg64();                       // if fail first try, use it as seed of simple lcg
for(;;) {
  uint32_t r = (seed >> 32) & mask;     // r at most bound bits (assumed top bits more random)
  if (r <= bound) return r;                       // done
  seed = lcg64(seed);                            // original seed very random, no need for another pcg
}

Think of lcg64 not as a random generator, but a regular math function (1 to 1 mapping)
The result will still be random if the seed itself is random.

**Comment by lemire** [comment]
Without even reviewing the code, I'd like just to point out that it is useful when stating that one's motivation is to speed things up, to include benchmarks.

**Comment by achan001** [comment]
I tried masking method and compare with integer mod (twice), masking bits is faster.
If bound is 32 bits (50% chance?), the 2 integer mods are just wasted ops.
Because pcg64 is very fast, even with small bound, I am still ahead.

This method is what the author of pcg referred as the division technique:
(But faster and more accurate without actual division)

https://github.com/imneme/pcg-c/blob/master/include/pcg_variants.h, line 837-841:

 *     (Note that using modulo is only wise for good RNGs, poorer RNGs
 *     such as raw LCGs do better using a technique based on division.)
 *     Empricical tests show that division is preferable to modulus for
 *     reducting the range of an RNG.  It's faster, and sometimes it can
 *     even be statistically prefereable.

my post is more about the second part, speed-up using simple lcg64 for repeated loops.

If randomness is the seed, lcg64 is regular function (1 to 1 mapping), it is probably overkill
to loop with pcg64.  Does it sound right ?

**Comment by achan001** [comment]
After some thinking, loop with lcg idea does NOT work.

For example, an extremely bad lcg, say (x + 1) mod 2^64
ALL input r > bound will return 0 (after MANY loops)

A good lcg (say Knuth MMIX) + very random seed probably is good enough.
Is there test programs for bounded random numbers ? (not bits or bytes)
